### ISSUE TITLE
Excessive log output

### ISSUE THREAD

**Issue by khurram18** [zendesk/Suas-iOS#29]
There is an excessive log output even when I am not using any `LoggerMiddleware`. How can I turn off this log output. I am using latest Suas version from cocoapods.

This log output is causing a significant burden on UI thread and is causing a very bad user experience.

**Comment by cloud9999strife** [comment]
I had the same issue, I made some changes and submitted a pull request. If you use the latest master from this repo you will be able to do this:
`Suas.enableDebugLogging = false`

This fixes the issue.

**Comment by baz8080** [comment]
I believe this is mitigated by https://github.com/zendesk/Suas-iOS/pull/27 and https://github.com/zendesk/Suas-iOS/pull/26
