### ISSUE TITLE
pod 'Suas' in podfile doesn't install latest suas release

### ISSUE THREAD

**Issue by cloud9999strife** [zendesk/Suas-iOS#36]
When I have `pod 'Suas'` in my podfile and do a `pod install` after doing` pod repo update`, I get the 1.0.0 version of Suas instead of the 1.1 version.

**Comment by KillianSmith0** [comment]
Hi @cloud9999strife 

Apologies for the lack of maintenance, we have updated the pod version.. Ryun `pod update` and it should go to v1.1

Feel free to open any other issues,
Killian
